spring:
  dubbo:
    scan: com.minstone.mobile.test.service
    application:
      name: mobile
    registry:
      protocol: "zookeeper"
      address: "127.0.0.1:2181"

    protocol:
      name: dubbo
      port: 20882
