spring:
  dubbo:
    scan: com.minstone.mobile.demo.service.impl
    application:
      name: consumer
    registry:
      protocol: "zookeeper"
      # 多注册中心如何处理？
      address: "127.0.0.1:2181"
#  main:
#    banner-mode: "off"
#  devtools:
#    restart:
#      trigger-file: .trigger